import Head from "next/head";
import React from "react";
import Footer from "./Footer";
import Navbar from "./Navbar";

function Layout({ title, desc, children }) {
  return (
    <div>
      <Head>
        <title>{title ? title : "JL ENTERPRISE"}</title>
        <meta
          name="description"
          content={desc ? desc : "Generated by create next app"}
        />
        <meta
          name="viewport"
          charSet="utf-8"
          content="width=device-width, initial-scale=1.0"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="main">{children}</div>
      <Footer/>
    </div>
  );
}

export default Layout;
